---

- hosts: all
  gather_facts: false
  vars:
    num_messages: 50
  tasks:
    - name: "debug1"
      debug:
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
    - name: "debug2"
      debug:
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
    - name: "debug3"
      debug: 
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
