- hosts: localhost
  gather_facts: false
  vars:
    uuid: "{{ 9999999999999999999999 | random | to_uuid }}"
    playbook_name: ""
    module_name: "tower_organization"
    module_args:
      name: "gigitty"
    check_mode: no

  tasks:
    - name: "Invoke random playbook name"
      set_fact:
        playbook_name: "/tmp/invoke_x_include_{{ uuid }}.yml"

    - name: Do dynamic playbook
      block:
        - name: "Create playbook to call module_name and module_args"
          template:
            src: invoke_x_template.j2
            dest: "{{ playbook_name }}"

        - include: "{{ playbook_name }}"

      always:
        - name: "Delete dynamic playbook"
          file:
            path: "{{ playbook_name }}"
            state: absent

