---
- hosts: localhost
  gather_facts: false
  vars:
    collection_id: awx.awx
  collections:
    - "{{ collection_id }}"
  tasks:
    - name: "Invoke tests for tower module {{ tower_module_under_test }}"
      include_tasks: "tower_{{ tower_module_under_test }}/tasks/main.yml"
